### ISSUE TITLE
thanks a lot

### ISSUE THREAD

**Issue by shenyx110** [KedisPL/Reforged-Fabric-API#1]
Hello, I'm making a simplified Chinese language file with your other mod Exotelcraft, but it's difficult to use in China legacy curseforge. I hope to submit it here. In addition, thank you very much for bringing me the feeling of childhood.

**Comment by KedisPL** [comment]
Yeah you can submit it here, but in future please don't. It's for reporting bugs for Reforged Fabric API. You can join my discord server if you want https://discord.com/invite/q88hexpX5R

**Comment by KedisPL** [comment]
I made a channel on my discord server for translating Exotelcraft https://discord.com/channels/870666302673543208/1140563738727030854
